name: Python application

on:
  schedule:
    - cron: '50 18 * * *'
  workflow_dispatch:    

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: |
        npm i peviitor_jsscraper
        
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 setup.py develop
    - name: Runing Scrapers
      env: 
        APIKEY: ${{ secrets.APIKEY }}
        Grasum_Key: ${{ secrets.GRASUM_KEY }}
      run: |
        python3 sites/main.py
