# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    -
    - name: Install dependencies
      run: |
        sudo apt-get install firefox-geckodriver 
        python3 -m pip install --upgrade pip
        python3 -m venv env
        source env/bin/activate
        echo "virtualenv activated: "$VIRTUAL_ENV
        export apikey="182b157-bb68-e3c5-5146-5f27dcd7a4c8"
        echo "apikey: "$apikey
        pip3 install -e .

    - name: Runing Scrapers
      run: |
        python3 sites/main.py
