name: Run test

on: pull_request

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python3 setup.py develop
    - name: Run test
      run: |
        git diff --name-only main
        # python3 __test__/runTest.py
